import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.review.deleteMany();
  await prisma.restaurant.deleteMany();
  await prisma.user.deleteMany();

  // Create dummy users
  const users = await Promise.all([
    prisma.user.create({ data: { name: 'Alice Smith', email: 'alice@example.com', passwordHash: 'hashedpassword', role: 'USER' } }),
    prisma.user.create({ data: { name: 'Bob Johnson', email: 'bob@example.com', passwordHash: 'hashedpassword', role: 'USER' } }),
    prisma.user.create({ data: { name: 'Charlie Davis', email: 'charlie@example.com', passwordHash: 'hashedpassword', role: 'USER' } }),
  ]);

  const restaurants = [
    { name: 'Chez Lumière', cuisine: 'French Continental', address: 'Lazimpat Road, Kathmandu', locationArea: 'Lazimpat', description: 'Candlelit booths, exceptional wine cellar and flawless French cuisine. The most intimate dining room in Kathmandu.', priceLevel: '$$$$', minPrice: 2500, maxPrice: 8000, capacity: 40, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '18:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 9, vibeEnergy: 2, vibeFormality: 9, vibeNoise: 2, vibeOutdoorsy: 1, averageRating: 4.8, reviewCount: 124, isFeatured: true },
    { name: 'Olive Garden Terrace', cuisine: 'Mediterranean', address: 'Durbar Marg, Kathmandu', locationArea: 'Durbar Marg', description: 'Rooftop garden draped in fairy lights overlooking Durbar Marg. Perfect for a special evening.', priceLevel: '$$$', minPrice: 1500, maxPrice: 5000, capacity: 60, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '17:00', closingTime: '23:30', imageUrl: 'https://images.unsplash.com/photo-1414235077428-33898ed1e830?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 8, vibeEnergy: 3, vibeFormality: 7, vibeNoise: 3, vibeOutdoorsy: 9, averageRating: 4.6, reviewCount: 98 },
    { name: 'Sakura Garden', cuisine: 'Japanese', address: 'Jhamsikhel, Patan', locationArea: 'Patan', description: 'Serene zen garden setting with an authentic sake bar and tatami-style seating.', priceLevel: '$$$', minPrice: 1800, maxPrice: 5500, capacity: 35, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '12:00', closingTime: '22:30', imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 9, vibeEnergy: 2, vibeFormality: 8, vibeNoise: 1, vibeOutdoorsy: 4, averageRating: 4.7, reviewCount: 76 },
    { name: 'The Moonlit Table', cuisine: 'Fusion', address: 'Boudha Ring Road, Kathmandu', locationArea: 'Boudha', description: "Candlelit rooftop with an ethereal stupa view and a chef's tasting menu that changes nightly.", priceLevel: '$$$', minPrice: 2000, maxPrice: 6000, capacity: 28, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '18:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 9, vibeEnergy: 2, vibeFormality: 7, vibeNoise: 2, vibeOutdoorsy: 6, averageRating: 4.9, reviewCount: 52, isFeatured: true },
    { name: 'The Masala Table', cuisine: 'Indian', address: 'Thamel Marg, Kathmandu', locationArea: 'Thamel', description: 'Buzzing rooftop bar with live music every Friday, a signature cocktail menu and bold Indian street food.', priceLevel: '$$', minPrice: 600, maxPrice: 2500, capacity: 120, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '11:00', closingTime: '23:30', imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 2, vibeEnergy: 9, vibeFormality: 3, vibeNoise: 8, vibeOutdoorsy: 8, averageRating: 4.5, reviewCount: 312 },
    { name: 'Himalayan Brewhouse', cuisine: 'Pub & Grill', address: 'Mandala Street, Thamel', locationArea: 'Thamel', description: '14 craft beers on tap, DJ sets every weekend and a packed dance floor. The liveliest spot in Thamel.', priceLevel: '$$', minPrice: 500, maxPrice: 2200, capacity: 150, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '12:00', closingTime: '00:00', imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 1, vibeEnergy: 10, vibeFormality: 1, vibeNoise: 9, vibeOutdoorsy: 4, averageRating: 4.2, reviewCount: 89 },
    { name: 'Tacos & Tequila Bar', cuisine: 'Mexican', address: 'Jhamsikhel Road, Patan', locationArea: 'Patan', description: 'Over 40 premium tequilas, authentic tacos and salsa nights every Saturday.', priceLevel: '$$', minPrice: 700, maxPrice: 2800, capacity: 80, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '12:00', closingTime: '23:30', imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 2, vibeEnergy: 9, vibeFormality: 2, vibeNoise: 9, vibeOutdoorsy: 5, averageRating: 4.3, reviewCount: 201 },
    { name: 'Namaste Rooftop', cuisine: 'Pan-Asian', address: 'Thamel Chowk, Kathmandu', locationArea: 'Thamel', description: '360° panoramic views of the Kathmandu valley, vibrant crowd, fire poi shows on weekends.', priceLevel: '$$', minPrice: 500, maxPrice: 2000, capacity: 200, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '10:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 2, vibeEnergy: 8, vibeFormality: 2, vibeNoise: 8, vibeOutdoorsy: 10, averageRating: 4.4, reviewCount: 445 },
    { name: 'The Reading Room Café', cuisine: 'Light Bites & Coffee', address: 'Lazimpat Lane, Kathmandu', locationArea: 'Lazimpat', description: 'Quiet, book-lined walls, specialty single-origin coffee and light bites. The perfect escape.', priceLevel: '$', minPrice: 200, maxPrice: 800, capacity: 25, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: true, openingTime: '07:00', closingTime: '20:00', imageUrl: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 7, vibeEnergy: 2, vibeFormality: 2, vibeNoise: 2, vibeOutdoorsy: 2, averageRating: 4.8, reviewCount: 178 },
    { name: 'Himal Lounge', cuisine: 'Continental Fusion', address: 'Boudha Stupa Circle', locationArea: 'Boudha', description: 'Co-working-friendly café with open-air seating, a clear stupa view and reliably good coffee.', priceLevel: '$', minPrice: 250, maxPrice: 900, capacity: 45, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '08:00', closingTime: '21:00', imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 5, vibeEnergy: 3, vibeFormality: 2, vibeNoise: 3, vibeOutdoorsy: 7, averageRating: 4.4, reviewCount: 93 },
    { name: 'Garden of Dreams Bistro', cuisine: 'Continental', address: 'Kaiser Mahal, Tridevi Marg', locationArea: 'Thamel', description: 'Set inside a 19th century heritage garden — jazz on Sundays, light brunch and peaceful atmosphere.', priceLevel: '$$', minPrice: 400, maxPrice: 1800, capacity: 70, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '09:00', closingTime: '21:00', imageUrl: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 2, vibeFormality: 4, vibeNoise: 2, vibeOutdoorsy: 9, averageRating: 4.6, reviewCount: 220 },
    { name: 'Café de Patan', cuisine: 'Nepali Fusion', address: 'Patan Durbar Square', locationArea: 'Patan', description: 'Tucked into a 16th-century courtyard, this hidden gem serves fusion Newari dishes with herbal teas.', priceLevel: '$', minPrice: 300, maxPrice: 1200, capacity: 30, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: true, openingTime: '08:00', closingTime: '20:00', imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 3, vibeFormality: 2, vibeNoise: 3, vibeOutdoorsy: 7, averageRating: 4.7, reviewCount: 134 },
    { name: 'Chimney Restaurant', cuisine: 'Continental', address: 'Yak & Yeti Hotel, Durbar Marg', locationArea: 'Durbar Marg', description: "Kathmandu's original power-lunch destination since the 1970s. Impeccable service, private booths, hushed tones.", priceLevel: '$$$$', minPrice: 3000, maxPrice: 9000, capacity: 60, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '12:00', closingTime: '22:30', imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 5, vibeEnergy: 2, vibeFormality: 9, vibeNoise: 2, vibeOutdoorsy: 1, averageRating: 4.7, reviewCount: 88 },
    { name: 'Chez Caroline', cuisine: 'French Bistro', address: 'Lazimpat, Kathmandu', locationArea: 'Lazimpat', description: 'Quiet French bistro with a set business lunch menu, private meeting booths and excellent coffee.', priceLevel: '$$$', minPrice: 1200, maxPrice: 4000, capacity: 40, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '11:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 2, vibeFormality: 8, vibeNoise: 2, vibeOutdoorsy: 1, averageRating: 4.5, reviewCount: 67 },
    { name: '1905 Restaurant', cuisine: 'Continental', address: 'Babar Mahal Revisited, Kathmandu', locationArea: 'Durbar Marg', description: 'Dine inside a restored Rana palace. Elegant setting ideal for important meetings and client entertaining.', priceLevel: '$$$', minPrice: 1500, maxPrice: 4500, capacity: 80, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '11:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 5, vibeEnergy: 2, vibeFormality: 9, vibeNoise: 2, vibeOutdoorsy: 3, averageRating: 4.6, reviewCount: 102 },
    { name: 'Baithak Café', cuisine: 'Continental Fusion', address: 'Thamel Heritage Zone', locationArea: 'Thamel', description: 'Heritage courtyard with private cabanas — a quiet island amid busy Thamel, perfect for working lunches.', priceLevel: '$$', minPrice: 600, maxPrice: 2000, capacity: 50, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '09:00', closingTime: '21:00', imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 2, vibeFormality: 7, vibeNoise: 3, vibeOutdoorsy: 5, averageRating: 4.3, reviewCount: 55 },
    { name: 'Thakali Kitchen', cuisine: 'Traditional Nepali', address: 'Jhamsikhel, Patan', locationArea: 'Patan', description: 'Unlimited dal bhat served in traditional copper thalis. Warm, spacious and universally loved.', priceLevel: '$$', minPrice: 400, maxPrice: 1200, capacity: 180, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '10:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 3, vibeEnergy: 6, vibeFormality: 2, vibeNoise: 6, vibeOutdoorsy: 2, averageRating: 4.9, reviewCount: 540, isFeatured: true },
    { name: 'Bhojan Griha', cuisine: 'Traditional Nepali', address: 'Dilli Bazaar, Kathmandu', locationArea: 'Baneshwor', description: '150-year-old palace venue with a live cultural dance show during dinner. A family experience like no other.', priceLevel: '$$$', minPrice: 1200, maxPrice: 3500, capacity: 250, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '11:00', closingTime: '22:30', imageUrl: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 3, vibeEnergy: 7, vibeFormality: 4, vibeNoise: 6, vibeOutdoorsy: 3, averageRating: 4.8, reviewCount: 310 },
    { name: 'Roadhouse Café', cuisine: 'Multi-cuisine', address: 'Thamel, Kathmandu', locationArea: 'Thamel', description: "Three floors, a dedicated kids' menu, generous portions and something for every taste. The reliable family pick.", priceLevel: '$$', minPrice: 350, maxPrice: 1500, capacity: 200, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '09:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1482275548304-a58859dc31b7?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 3, vibeEnergy: 7, vibeFormality: 2, vibeNoise: 7, vibeOutdoorsy: 3, averageRating: 4.3, reviewCount: 487 },
    { name: 'Momo Mama', cuisine: 'Nepali Street Food', address: 'Baneshwor Chowk, Kathmandu', locationArea: 'Baneshwor', description: '20+ varieties of handmade momos — steamed, fried, jhol and even chocolate dessert momos. Kids go wild here.', priceLevel: '$', minPrice: 120, maxPrice: 450, capacity: 80, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '10:00', closingTime: '21:00', imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 3, vibeEnergy: 8, vibeFormality: 1, vibeNoise: 8, vibeOutdoorsy: 4, averageRating: 4.6, reviewCount: 623 },
    { name: 'Yak & Yeti Coffee House', cuisine: 'Nepali Continental', address: 'Durbar Marg, Kathmandu', locationArea: 'Durbar Marg', description: 'Timeless Kathmandu institution. Sit with a newspaper, order the legendary apple pie and feel completely at home.', priceLevel: '$$', minPrice: 500, maxPrice: 1800, capacity: 90, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '07:30', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 2, vibeFormality: 4, vibeNoise: 2, vibeOutdoorsy: 2, averageRating: 4.5, reviewCount: 289 },
    { name: 'OR2K Restaurant', cuisine: 'Middle Eastern Vegetarian', address: 'Thamel, Kathmandu', locationArea: 'Thamel', description: "Floor cushion seating, chill music, massive vegetarian menu and zero pressure to leave. Solo traveller's haven.", priceLevel: '$', minPrice: 250, maxPrice: 1000, capacity: 60, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: true, openingTime: '08:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1544025162-d76538b2a5b1?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 2, vibeFormality: 1, vibeNoise: 2, vibeOutdoorsy: 3, averageRating: 4.4, reviewCount: 192 },
    { name: "Dwarika's Heritage Bar", cuisine: 'Cocktails & Tapas', address: 'Battisputali, Kathmandu', locationArea: 'Baneshwor', description: 'Inside a UNESCO-recognised heritage hotel. Hand-crafted cocktails, rare spirits and a soaring wooden interior.', priceLevel: '$$$$', minPrice: 2000, maxPrice: 6000, capacity: 50, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '17:00', closingTime: '23:30', imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 6, vibeFormality: 8, vibeNoise: 4, vibeOutdoorsy: 3, averageRating: 4.9, reviewCount: 143, isFeatured: true },
    { name: 'Summit Hotel Roof Garden', cuisine: 'Continental', address: 'Kopundole, Patan', locationArea: 'Patan', description: 'Himalayan panorama, white tablecloths and a champagne terrace. The go-to for anniversaries and big occasions.', priceLevel: '$$$', minPrice: 1800, maxPrice: 5000, capacity: 100, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '12:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 6, vibeEnergy: 6, vibeFormality: 7, vibeNoise: 4, vibeOutdoorsy: 8, averageRating: 4.7, reviewCount: 204 },
    { name: 'Krishnarpan', cuisine: 'Nepali Fine Dining', address: "Dwarika's Hotel, Battisputali", locationArea: 'Baneshwor', description: 'A legendary 6-to-22 course Nepali tasting journey. The ultimate celebration of Nepali gastronomy.', priceLevel: '$$$$', minPrice: 4000, maxPrice: 12000, capacity: 30, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '18:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 7, vibeEnergy: 5, vibeFormality: 9, vibeNoise: 3, vibeOutdoorsy: 2, averageRating: 5.0, reviewCount: 88 },
    { name: 'Nanglo Pub & Pastry', cuisine: 'Nepali Continental', address: 'Durbar Marg, Kathmandu', locationArea: 'Durbar Marg', description: "Since 1978, the iconic Nanglo has been the city's first stop for celebrations, legendary pastries and reunions.", priceLevel: '$$', minPrice: 400, maxPrice: 1800, capacity: 120, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '08:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 5, vibeEnergy: 7, vibeFormality: 5, vibeNoise: 6, vibeOutdoorsy: 4, averageRating: 4.6, reviewCount: 378 },
    { name: 'Gaia Restaurant', cuisine: 'International Fusion', address: 'Pokhara Lakeside', locationArea: 'Pokhara', description: 'Fewa Lake views, adventurous fusion dishes and an open kitchen concept. For the bold and hungry explorer.', priceLevel: '$$', minPrice: 600, maxPrice: 2500, capacity: 90, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '11:00', closingTime: '23:00', imageUrl: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 3, vibeEnergy: 7, vibeFormality: 2, vibeNoise: 6, vibeOutdoorsy: 10, averageRating: 4.7, reviewCount: 167 },
    { name: 'Pokhara Grande Rooftop', cuisine: 'Multi-cuisine', address: 'Pokhara, Lakeside North', locationArea: 'Pokhara', description: 'DJ Saturdays with a panoramic view of the Annapurna range. A dining experience that doubles as a full night out.', priceLevel: '$$$', minPrice: 800, maxPrice: 3500, capacity: 180, parkingTwoWheeler: true, parkingFourWheeler: true, isVeg: false, openingTime: '12:00', closingTime: '23:30', imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?q=80&w=800&auto=format&fit=crop', status: 'LIVE', vibeIntimacy: 2, vibeEnergy: 9, vibeFormality: 3, vibeNoise: 8, vibeOutdoorsy: 10, averageRating: 4.5, reviewCount: 241 },
    { name: 'Fire & Ice Pizzeria', cuisine: 'Italian', address: 'Sanchal Marg, Thamel', locationArea: 'Thamel', description: 'Wood-fired pizzas and homemade gelato. A Kathmandu institution since 1994.', priceLevel: '$$', minPrice: 500, maxPrice: 1800, capacity: 110, parkingTwoWheeler: true, parkingFourWheeler: false, isVeg: false, openingTime: '11:00', closingTime: '22:00', imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800&auto=format&fit=crop', status: 'PENDING', vibeIntimacy: 5, vibeEnergy: 5, vibeFormality: 5, vibeNoise: 5, vibeOutdoorsy: 5 },
  ];

  const createdRestaurants = [];
  for (const r of restaurants) {
    const created = await prisma.restaurant.create({ data: r as any });
    createdRestaurants.push(created);
  }
  console.log(`✅ Seeded ${restaurants.length} restaurants!`);

  // Add pseudo reviews
  const reviewComments = [
    "Absolutely loved the vibe here! The food was amazing.",
    "Great place, but a bit too noisy for my liking.",
    "A hidden gem! Highly recommend for a date night.",
    "Good service, decent prices. Will come back.",
    "The atmosphere is incredible, the staff is so friendly.",
  ];

  for (const restaurant of createdRestaurants) {
    // Add 2-3 reviews per restaurant
    const numReviews = Math.floor(Math.random() * 2) + 2;
    for (let i = 0; i < numReviews; i++) {
      const randomUser = users[Math.floor(Math.random() * users.length)];
      const randomComment = reviewComments[Math.floor(Math.random() * reviewComments.length)];
      const randomRating = Math.floor(Math.random() * 2) + 4; // 4 or 5 stars

      await prisma.review.create({
        data: {
          rating: randomRating,
          comment: randomComment,
          userId: randomUser.id,
          restaurantId: restaurant.id,
        }
      });
    }
  }
  console.log(`✅ Seeded pseudo reviews!`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
